name: Cypress

on:
  push:
    branches:
      - "t2-6-automatizado"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    name: End-to-end
    runs-on: ubuntu-24.04

    env:
      VITE_GRAPHQL_API_URL: http://localhost:4000/graphql

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Ejecutar Cypress E2E
        uses: cypress-io/github-action@v7
        with:
          start: npm run dev -- --host 0.0.0.0
          wait-on: "http://localhost:5173"

      - name: Guardar capturas de fallos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-e2e-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

  component:
    name: Component testing
    runs-on: ubuntu-24.04

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Ejecutar Cypress Component
        uses: cypress-io/github-action@v7
        with:
          component: true

      - name: Guardar capturas de fallos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-component-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
